# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailpit < Formula
  desc "An email and SMTP testing tool with API for developers"
  homepage "https://github.com/axllent/mailpit"
  version "1.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/axllent/mailpit/releases/download/v1.3.7/mailpit-darwin-arm64.tar.gz"
      sha256 "48a586425789c36346465baeedecb6248da786f8dbe6c8213aa755df3c5ebb31"

      def install
        bin.install "mailpit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axllent/mailpit/releases/download/v1.3.7/mailpit-darwin-amd64.tar.gz"
      sha256 "2d88dd20bc619c21fea0541c6b76ba885c874a8072c39148a3122ac96f40e460"

      def install
        bin.install "mailpit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/axllent/mailpit/releases/download/v1.3.7/mailpit-linux-amd64.tar.gz"
      sha256 "50782905fade4b44b088a43e2328190c4cca71b9989b2538dfb2402dfe028e8c"

      def install
        bin.install "mailpit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axllent/mailpit/releases/download/v1.3.7/mailpit-linux-arm64.tar.gz"
      sha256 "11982f23bde00a5a8ffbb85ca98bf43b6758c82f4b23dc6d5da0f91e0917410a"

      def install
        bin.install "mailpit"
      end
    end
  end

  service do
    run "#{bin}/mailpit"
    keep_alive true
    log_path var/"log/mailpit.log"
    error_log_path var/"log/mailpit.log"
  end

  test do
    address = "127.0.0.1:#{free_port}"
    fork { exec "#{bin}/mailpit", "--listen", address }
    sleep 2

    output = shell_output("curl --silent #{address}")
    assert_match "<title>MailPit</title>", output
  end
end
