# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SymfonyCli < Formula
  desc "An email and SMTP testing tool with API for developers"
  homepage "https://github.com/axllent/mailpit"
  version "1.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/axllent/mailpit/releases/download/v1.3.6/mailpit-darwin-arm64.tar.gz"
      sha256 "8e9cfb8bd6a5a95dc0593d83d65ad34a603d26305f554b88ba41bb761b9456de"

      def install
        bin.install "mailpit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/axllent/mailpit/releases/download/v1.3.6/mailpit-darwin-amd64.tar.gz"
      sha256 "ae8ad742e74af81f943f9e06d5dba81ded49d20e19d4bd0206bfbc167a2578ce"

      def install
        bin.install "mailpit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/axllent/mailpit/releases/download/v1.3.6/mailpit-linux-amd64.tar.gz"
      sha256 "e1e8ba9625eef0d55f3ebec2bf5718638929141f92929e3fcb6f2c2526440112"

      def install
        bin.install "mailpit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axllent/mailpit/releases/download/v1.3.6/mailpit-linux-arm64.tar.gz"
      sha256 "7774c35fbceb610d91d9f445ea0971dd3c48bebbd482be7287c1c36fefb7a522"

      def install
        bin.install "mailpit"
      end
    end
  end

  service do
    run "#{bin}/mailpit"
    keep_alive true
    log_path var/"log/mailpit.log"
    error_log_path var/"log/mailpit.log"
  end

  test do
    system "#{bin}/mailpit version"
  end
end
